name: wp-360configurator

services:
  wordpress-configurator:
    container_name: wp-360configurator-wordpress
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
    env_file:
      - .env
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/plugins:delegated
      - ./wp-content/themes:/var/www/html/wp-content/themes:delegated
    links:
      - mysql-configurator
    networks:
      - wpconfigurator
  mysql-configurator:
    container_name: wp-360configurator-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - wpconfigurator
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'wp'
      MYSQL_USER: 'wp'
      MYSQL_PASSWORD: 'wp'
networks:
  wpconfigurator:
    external: false